version: '3.1'
services:

    redis:
        image: redis:alpine
        container_name: rawilk-webauthn-api-redis
        healthcheck:
            test: [ "CMD", "redis-cli", "ping" ]
            interval: 30s
            timeout: 10s
            retries: 5

    postgres:
        image: postgres:13
        working_dir: /var/www/api
        container_name: webauthn-postgres
        restart: unless-stopped
        environment:
            POSTGRES_USER: laravel
            POSTGRES_PASSWORD: laravel
            POSTGRES_DB: laravel
        volumes:
            - .:/var/www/api
        ports:
            - "5433:5433"

    webserver:
        image: nginx:alpine
        working_dir: /var/www/api
        container_name: rawilk-webauthn-api-webserver
        depends_on:
            - php-fpm
        volumes:
            - .:/var/www/api
            - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        ports:
            - '801:801'

    php-fpm:
        build: phpdocker/php-fpm
        working_dir: /var/www/api
        container_name: rawilk-webauthn-api-php-fpm
        environment:
            - XDEBUG_CONFIG=remote_host=172.0.0.1 remote_enable=1 mode=coverage
            - PHP_IDE_CONFIG=serverName=localhost
        depends_on:
            - postgres
            - redis
        volumes:
            - .:/var/www/api
            - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.1/fpm/conf.d/99-overrides.ini
            - ./phpdocker/php-fpm/xdebug.ini:/etc/php/8.1/mods-available/xdebug.ini

    php-horizon:
        build: phpdocker/supervisor
        working_dir: /var/www/api
        container_name: rawilk-webauthn-api-php-horizon
        depends_on:
            - php-fpm
        volumes:
            - .:/var/www/api
            - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.1/fpm/conf.d/99-overrides.ini
            - ./phpdocker/supervisor/conf.d:/etc/supervisor/conf.d

    php-scheduler:
        build: phpdocker/php-fpm
        working_dir: /var/www/api
        container_name: rawilk-webauthn-api-php-scheduler
        command: php /var/www/api /artisan schedule:work
        depends_on:
            - php-fpm
        volumes:
            - .:/var/www/api
            - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.1/fpm/conf.d/99-overrides.ini
            - ./phpdocker/supervisor/conf.d:/etc/supervisor/conf.d

    node:
        image: node:16
        working_dir: /var/www/api
        container_name: rawilk-webauthn-api-node
        environment:
            - NODE_ENV=local
        volumes:
            - ./:/var/www/api
        command: tail -f /dev/null
        depends_on:
            - php-fpm
